// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BoxNewComment: typeof import('./components/BoxNewComment.vue')['default']
    BoxPlayRecord: typeof import('./components/BoxPlayRecord.vue')['default']
    ButtonDownload: typeof import('./components/iconButton/ButtonDownload.vue')['default']
    ButtonHeart: typeof import('./components/iconButton/ButtonHeart.vue')['default']
    ButtonPlay: typeof import('./components/ButtonPlay.vue')['default']
    ButtonPlayAll: typeof import('./components/iconButton/ButtonPlayAll.vue')['default']
    ButtonSubscribe: typeof import('./components/ButtonSubscribe.vue')['default']
    ButtonThumbUp: typeof import('./components/iconButton/ButtonThumbUp.vue')['default']
    Cover: typeof import('./components/Cover.vue')['default']
    ListComment: typeof import('./components/ListComment.vue')['default']
    ListSong: typeof import('./components/ListSong.vue')['default']
    MusicPlayer: typeof import('./components/musicPlayer/MusicPlayer.vue')['default']
    MusicPlayerController: typeof import('./components/musicPlayer/MusicPlayerController.vue')['default']
    MusicPlayerDisable: typeof import('./components/musicPlayer/MusicPlayerDisable.vue')['default']
    MusicPlayerProgress: typeof import('./components/musicPlayer/MusicPlayerProgress.vue')['default']
    PlayCountInner: typeof import('./components/iconButton/playCountInner.vue')['default']
    PlayerMode: typeof import('./components/iconButton/playerMode.vue')['default']
    PlayInnerRed: typeof import('./components/iconButton/playInnerRed.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgDate: typeof import('./components/iconButton/SvgDate.vue')['default']
    SvgVolume: typeof import('./components/iconButton/SvgVolume.vue')['default']
    TheDailyCover: typeof import('./components/TheDailyCover.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheFooterLeft: typeof import('./components/TheFooterLeft.vue')['default']
    TheFooterRight: typeof import('./components/TheFooterRight.vue')['default']
    TheLyricParser: typeof import('./components/TheLyricParser.vue')['default']
    ToggleMode: typeof import('./components/iconButton/toggleMode.vue')['default']
  }
}

export {}
